spring.application.name=spring_1_one

server.port=7001

#jsp 셋팅
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

	# 오라클 세팅
	spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
	spring.datasource.url=jdbc:oracle:thin:@1.245.91.227:1522/xe
	spring.datasource.username=c##jsl_spring_db
	spring.datasource.password=1234

	# mybatis
	mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
	mybatis.configuration.cache-enabled=false
	#mybatis에서 query 결과 null인경우 오류 해결
	mybatis.configuration.jdbc-type-for-null=NULL
	
	#dto pakage 경로 설정
	mybatis.type-aliases-package=com.kr.pjtone.dto

	# mapper.xml >>resulttype 경로 설정 resultType="MemberDto" package경로 생략가능
	#								  resultType="aaa.bbb.memberone.MemberDto"		 
	# 	<select id="getMemberList" resultType="MemberDto" parameterType="map">
	#		select ~~~~~	
	#	</select>
	# mybatis.type-aliases-package=aaa.bbb.memberone.dto